Use a renderable exception for OAuth errors
laravel/passport pull request #1066
Opened 2019-08-11 03:23 UTC by matt-allan

This PR updates the Passport controllers to use a renderable exception instead of middleware for rendering OAuth errors.

Originally Passport handled exception reporting and rendering itself, but developers wanted to be able to control the rendering so the behavior was moved to middleware in #937.

The problem with using middleware is the pipeline catches exceptions before they reach middleware (#1062).

The only reason Passport needed to handle exceptions in the first place was to convert the League exception's PSR response to something Laravel can render, so this PR wraps the League exception in a renderable Passport exception.

If the user wants to change how the exception is rendered they can do that in their application's exception handler.

I don't see any reason that Passport needs to override 500 error rendering so these fall through to the application's normal rendering.

**Upgrading::*

If you are explicitly handling `League\OAuth2\Server\Exception\OAuthServerException` in your exception handler's `report` method you will need to check for an instance of `Laravel\Passport\Exceptions\OAuthServerException` instead.

If for some reason your OAuth client's are relying on 500 errors returning the string `Error.` in the response you will need to override the rendering for `/oauth/authorize` and `/oauth/token`, i.e.

```php
public function render($request, Exception $e)
{
	if ($request->is('/oauth/authorize', '/oauth/token')) {
		return response('Error.', 500);
	}
}
```

2019-08-12 09:36 UTC, driesvints requested changes

2019-08-12 09:36 UTC, driesvints commented on src/Exceptions/OAuthServerException.php
> +     * @param  \Illuminate\Http\Request
```suggestion
     * @param  \Illuminate\Http\Request  $request
```

2019-08-12 09:36 UTC, driesvints commented on src/Http/Controllers/HandlesOAuthErrors.php
> +     *
```suggestion
```

2019-08-12 09:36 UTC, driesvints commented on tests/HandlesOAuthErrorsTest.php
> +        try {
```suggestion

        try {
```

2019-08-12 09:36 UTC, driesvints commented
Also rebase once to resolve the conflicts.

2019-08-12 21:14 UTC, matt-allan commented
Hey @driesvints, thanks for the review. I made the requested changes and rebased.

2019-08-13 09:17 UTC, driesvints requested changes
Heya, just some DocBlocks and we're good.

2019-08-13 09:17 UTC, driesvints commented on src/Exceptions/OAuthServerException.php
> +    protected $response;
Add a DocBlock here.

2019-08-13 09:17 UTC, driesvints commented on src/Exceptions/OAuthServerException.php
> +    public function __construct(LeagueException $e, Response $response)
Add a DocBlock here like on other constructors.

2019-08-13 20:46 UTC, matt-allan commented
@driesvints thanks, I added the docblocks and squashed.

2019-08-15 10:02 UTC, driesvints commented on src/Exceptions/OAuthServerException.php
> +    public function __construct(LeagueException $e, Response $response)
We use fully qualified namespaces in docblocks everywhere and two spaces before and after a type for `@param` annotations.

2019-08-19 14:35 UTC, driesvints commented
@matt-allan I'm going to re-open this if that's okay because we'll need this for the next release. Planning to work on Passport 8 in September so I'll take a look at this then.

2019-08-19 15:05 UTC, matt-allan commented
Sure, no problem.

2019-08-20 12:57 UTC, merged

2024-03-04 09:47 UTC, swh-cgm commented
@driesvints I am using passport 11.10.5. Can I still catch and render Passport's Laravel\Passport\Exceptions\OAuthServerException from Handler.php? 
I want to make a JSON response if the access token is expired. But I can only catch League\OAuth2\Server\Exception\OAuthServerException only on reportable function in Handler.php.

2024-08-01 19:04 UTC, biodunbamigboye commented
I faced this same issue today, and came out with a very simple though not syntactically elegant solution, but it works like magic
Inside Handler.php  add League\OAuth2\Server\Exception\OAuthServerException to $dontReport array then in render method, based on the message Log a custom error
`
use League\OAuth2\Server\Exception\OAuthServerException;

    protected $dontReport = [
        OAuthServerException::class
    ];

   public function render($request, Throwable $exception)
    {


        if ($exception->getMessage() === 'Unauthenticated.') {
          Log::error(json_encode([
// custom error
]));
          }
     }
`