[13.x] Support OAuth2 Server v9
laravel/passport pull request #1734
Opened 2024-03-29 15:59 UTC by hafezdivandari

WIP

2024-03-29 16:56 UTC, hafezdivandari commented
@driesvints this repo doesn't have `master` branch?

2024-03-29 21:38 UTC, jayan-blutui commented
Great work on creating this PR so quickly seeing v9rc just launched a couple of days ago.

I know this PR is still a WIP but do you plan to include the new Device Authorization?

2024-03-30 11:49 UTC, hafezdivandari commented
@jayan-blutui thanks.

> I know this PR is still a WIP but do you plan to include the new Device Authorization?

Not in this PR, as it makes this hard to review.

2024-04-02 08:09 UTC, driesvints commented
Thanks a lot for this PR @hafezdivandari. We should indeed try to support the new Device flow in v13 but let's indeed tackle that in a subsequent PR.

2024-04-02 08:12 UTC, driesvints requested changes

2024-04-02 08:12 UTC, driesvints commented on .gitignore
> +/.rnd
I'd prefer if you removed these and added these to a global gitignore file: https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files

2024-04-02 08:12 UTC, driesvints commented on composer.json
>          "illuminate/support": "^9.21|^10.0|^11.0",
In a next PR we may drop Laravel v9 and v10 support as well as PHP 8.1

2024-04-02 08:12 UTC, driesvints commented on src/Bridge/FormatsScopesForStorage.php
> +     * @param  ScopeEntityInterface[]  $scopes
Can we use FQN here?

2024-04-02 08:13 UTC, driesvints commented on .github/workflows/tests.yml
>          laravel: [9, 10, 11]
In a next PR we may drop Laravel v9 and v10 support as well as PHP 8.1

2024-04-14 22:48 UTC, hafezdivandari commented on composer.json
> +        "league/oauth2-server": "dev-fix-passport-compatibility",
TBD

2024-05-15 13:50 UTC, hafezdivandari commented
@driesvints This PR is ready, but it should target `master`, which doesn't exist on this repo.

2024-05-15 14:53 UTC, driesvints commented
@hafezdivandari that's okay. We're using a different approach these days. I'll talk to the team to prepare a new major version. Ideally we'd also take in the new device flow (separate PR).

Thanks for working on this one!

2024-05-15 14:57 UTC, driesvints approved these changes

2024-05-16 07:51 UTC, driesvints commented
@hafezdivandari I retargeted your PR to 13.x now

2024-05-16 09:23 UTC, siarheipashkevich commented
@hafezdivandari @driesvints why not to 12.x?

2024-05-16 11:49 UTC, driesvints commented
@siarheipashkevich there's just too many breaking changes in here.

@hafezdivandari reminds me: could you make a list of upgrade steps in `UPGRADE.md`? I think we only need to reference the OAuth Server client v9 upgrade and a link to its own release notes, telling people to review those as well: https://github.com/thephpleague/oauth2-server/blob/master/CHANGELOG.md#900---released-2024-05-13

2024-05-16 21:55 UTC, taylorotwell commented
Can someone give me an idea of the full upgrade steps and mark as ready for review?

2024-05-16 22:44 UTC, driesvints commented
@taylorotwell those are already added to the upgrade guide in this PR. The main reason for this new major version is the oauth server v9 bump and the method signature changes.

2024-05-16 23:03 UTC, hafezdivandari commented
@driesvints We are not going to release 13.x immediately after merging this right? I have 1 or 2 PRs for 13.x before release.

2024-05-16 23:06 UTC, driesvints commented
@hafezdivandari no I'll wait for those

2024-05-17 21:54 UTC, taylorotwell commented
@driesvints I guess I'm looking for a general summary of the changes someone will need to make. What changes will a typical Laravel Passport app need to make?

2024-05-17 21:59 UTC, hafezdivandari commented
@taylorotwell nothing, just PHP 8.1+ and removed `message` property from `OAuthException` HTTP response. Now just use `error_description` as per the OAuth 2 spec.

2024-05-17 22:05 UTC, merged